version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: "github-actions"
    directory: "/apps/api"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
  - package-ecosystem: npm
    directory: "/apps/web"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: fix
      prefix-development: chore
      include: scope
